machine:
  node:
    version: 4.6.0
  services:
    - docker
  environment:
    PACTBROKERURL: 'https://xebia.pact.dius.com.au/'
    MAPMAKERURL: 'http://etg-balancer-862594806.eu-central-1.elb.amazonaws.com:3000'
    HIGHSCOREURL: 'http://etg-balancer-862594806.eu-central-1.elb.amazonaws.com:4000'
    TAG: 'prod'
    JUNIT_REPORT_PATH: $CIRCLE_TEST_REPORTS/junit/
jobs:
  test:
    override:
      - npm run test:unit
      - npm run test:unit-int
      - node ./bin/www & cypress run --reporter junit --reporter-options "mochaFile=$CIRCLE_TEST_REPORTS/junit/cypress-test-output.xml,toConsole=true"
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/front:$CIRCLE_SHA1 .
      - docker run -d -p 2000:2000 -e HIGHSCOREURL=$HIGHSCOREURL -e MAPMAKERURL=$MAPMAKERURL --name front $AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/front:$CIRCLE_SHA1; sleep 10
      - curl -sSf http://localhost:2000 > /dev/null
  deployment:
    prod:
      branch: master
      commands:
        - npm run pact-publish
        - ./deploy.sh
        - curl -X POST https://circleci.com/api/v1.1/project/github/FinKingma/etg_e2e/tree/master?circle-token=67eb5218ceeb5094bf28a738072e00d3bc069642

Workflows:
  version: 1
  BDT:
    jobs:
    - test
    - deployment:
      type: approval
      requires:
      - test