version: 2
environment:
  PACTBROKERURL: 'https://xebia.pact.dius.com.au/'
  MAPMAKERURL: 'http://etg-balancer-862594806.eu-central-1.elb.amazonaws.com:3000'
  HIGHSCOREURL: 'http://etg-balancer-862594806.eu-central-1.elb.amazonaws.com:4000'
  TAG: 'prod'
  JUNIT_REPORT_PATH: $CIRCLE_TEST_REPORTS/junit/

jobs:
  build:
    docker:      
    - image: circleci/node:latest-browsers
    working_directory: ~/etg_scoring
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            npm install
      - run:
          name: run unit and component tests
          command: |
            export CHROME_BIN=google-chrome
            npm run test:unit
            npm run test:unit-int
  
  test:
    docker:      
    - image: finkingma/etg-highscore-ci:0.7.0
    working_directory: ~/etg_scoring
    steps:
      - checkout
      - run:
          name: install cypress
          command: |
            npm install cypress
      - run:
          name: run cypress
          command: |
            npm run test:web
      - setup_remote_docker
      - run:
          name: run docker test
          command: |
            docker build -t $AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/front:$CIRCLE_SHA1 .
            docker run -d -p 2000:2000 -e HIGHSCOREURL=$HIGHSCOREURL -e MAPMAKERURL=$MAPMAKERURL --name front $AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/front:$CIRCLE_SHA1; sleep 10
            curl -sSf http://localhost:2000 > /dev/null
  deploy:
    docker:      
    - image: finkingma/etg-highscore-ci:0.7.0
    working_directory: ~/etg_scoring
    steps:
      - checkout
      - run:
          name: deploy to aws
          command: |
            ./deploy.sh
            npm run pact-publish
  manual:
    docker:      
    - image: finkingma/etg-highscore-ci:0.7.0
    working_directory: ~/etg_scoring
    steps:
      - run: 
          name: doe spul
          command: echo gooo
workflows:
  version: 2
  BDT:
    jobs:
    - build
    - test:
        requires:
        - build
    - manual:
        type: approval
        requires:
        - test
    - deploy:
        requires:
        - manual