version: 2
environment:
  PACTBROKERURL: 'https://xebia.pact.dius.com.au/'
  MAPMAKERURL: 'http://etg-balancer-862594806.eu-central-1.elb.amazonaws.com:3000'
  HIGHSCOREURL: 'http://etg-balancer-862594806.eu-central-1.elb.amazonaws.com:4000'
  TAG: 'prod'
  JUNIT_REPORT_PATH: $CIRCLE_TEST_REPORTS/junit/

jobs:
  "build":
    docker:      
    - image: finkingma/etg-highscore-ci:0.7.0
    working_directory: ~/etg_scoring
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: run unit and component tests
          command: |
            npm run test:unit
            npm run test:unit-int
  
  "test":
    docker:      
    - image: finkingma/etg-highscore-ci:0.7.0
    working_directory: ~/etg_scoring
    steps:
      - checkout
      - run:
        name: run cypress
        command: |
          node ./bin/www & cypress run --reporter junit --reporter-options "mochaFile=$CIRCLE_TEST_REPORTS/junit/cypress-test-output.xml,toConsole=true"
      - setup_remote_docker
      - run:
        name: run docker test
        command: |
          docker build -t $AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/front:$CIRCLE_SHA1 .
          docker run -d -p 2000:2000 -e HIGHSCOREURL=$HIGHSCOREURL -e MAPMAKERURL=$MAPMAKERURL --name front $AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/front:$CIRCLE_SHA1; sleep 10
          curl -sSf http://localhost:2000 > /dev/null
  "deploy":
    steps:
      - checkout
      - run:
        name: deploy to aws
        command: |
          ./deploy.sh
          npm run pact-publish
  "manual":
    steps:
      - run: echo 'gooo'
workflows:
  version: 1
  BDT:
    jobs:
    - build
    - test
    - manual
      type: approval
      requires:
      - test
    - deploy:
      requires:
      - manual